---

services:
  trainer:
    build: .
    restart: unless-stopped
    runtime: nvidia
    ipc: host
    shm_size: '4gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TF_GPU_ALLOCATOR=cuda_malloc_async
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=8
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ../data:/app/data
      - ./checkpoints:/app/checkpoints
    command: >
      python src/main.py
      --config configs/config.yaml
      --mode train

  predict:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_CPP_MIN_LOG_LEVEL=2
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ../data:/app/data
      - ./checkpoints:/app/checkpoints
    command: >
      python src/main.py
      --config configs/config.yaml
      --mode test
      --model_path checkpoints/model_latest